### ISSUE TITLE
Updating embedded objects

### ISSUE THREAD

**Issue by zoresvit** [eBay/YiDB#6]
Hi and thanks for open sourcing a cool configuration management database solution!

I'm having problems with modifying embedded objects via YiDB API. Conceptually I have a `Server` object that contains references to `Interface` as embedded objects (one-to-many relationship). So that when the server is deleted, interfaces are also deleted automatically. 

But when trying to modify interfaces by modifying the `Server` object, modifications just won't apply, no errors are produced. 

So far I could only delete a new `Server` object with updated interfaces and delete the old one.

Is there any better way of doing this with YiDB API?

Thank you.

**Comment by zhihzhang** [comment]
Hi, 

Thank you for using YiDB. 
For embedded objects, YiDB doesn't allow to modify Interfaces by modifying the server object. 
If you need to update/delete Interface objects, you can use normal update/delete api. If you delete an Interface, their reference with Server will be deleted too.
If you want to create an interface object, you need to paas "path" attribute in create api. For instance, the "path" for create interface object will be like
Server!5365e8d34f5af8c5c355aeeb!Interface

Btw, for your use case, I think you can use Inner reference instead.
Here is the introduction of inner reference
An inner class could not be created standalone. Its life-cycle is managed by its host class.YiDB supports cascading deletion when deleting host class object. E.g. The inner class objects should be deleted recursively.

Please let me know if you have any questions.

Thanks & Regards
Al Zhang
